// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Browser.H>

class UserInterface {
public:
  UserInterface();
protected:
  Fl_Double_Window *janela;
public:
  Fl_Button *Botao_Salvar;
  Fl_Box *Projeto_Aberto;
  Fl_Button *Botao_Gerar;
  Fl_Button *Botao_Abrir_Carregar;
  Fl_Input *Titulo_Input;
  Fl_Browser *Navegador;
  Fl_Button *Botao_Deletar;
  Fl_Button *Botao_Inserir;
  Fl_Button *Botao_Alterar;
  Fl_Input *Botao_Editar;
  Fl_Button *Botao_Limpar;
};
#endif
