// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "window.h"

UserInterface::UserInterface() {
  { janela = new Fl_Double_Window(450, 500, "Web Editor");
    janela->box(FL_EMBOSSED_BOX);
    janela->user_data((void*)(this));
    { Botao_Salvar = new Fl_Button(10, 405, 215, 35, "Salvar Projeto");
    } // Fl_Button* Botao_Salvar
    { Projeto_Aberto = new Fl_Box(5, 4, 440, 36, "Nenhum projeto ou template carregado!");
    } // Fl_Box* Projeto_Aberto
    { Botao_Gerar = new Fl_Button(230, 405, 210, 35, "Gerar Index.HTML");
    } // Fl_Button* Botao_Gerar
    { Botao_Abrir_Carregar = new Fl_Button(10, 450, 430, 40, "Abrir e carregar arquivos projeto.csv e template.html");
    } // Fl_Button* Botao_Abrir_Carregar
    { Titulo_Input = new Fl_Input(50, 52, 385, 43, "T\303\255tulo");
    } // Fl_Input* Titulo_Input
    { Navegador = new Fl_Browser(10, 145, 430, 150, "IDS/LABELS");
      Navegador->type(2);
    } // Fl_Browser* Navegador
    { Botao_Deletar = new Fl_Button(310, 315, 130, 30, "Deletar");
    } // Fl_Button* Botao_Deletar
    { Botao_Inserir = new Fl_Button(170, 315, 130, 30, "Inserir");
    } // Fl_Button* Botao_Inserir
    { Botao_Alterar = new Fl_Button(10, 315, 150, 30, "Alterar");
    } // Fl_Button* Botao_Alterar
    { Botao_Editar = new Fl_Input(55, 111, 260, 29, "Editor");
    } // Fl_Input* Botao_Editar
    { Botao_Limpar = new Fl_Button(325, 110, 110, 30, "Limpar");
    } // Fl_Button* Botao_Limpar
    { Caixa_Botoes = new Fl_Input(135, 359, 305, 31, "Bot\303\265""es de Op\303\247\303\243o");
    } // Fl_Input* Caixa_Botoes
    janela->end();
  } // Fl_Double_Window* janela
}
